export const FETCH = 'FETCH';
export const UPDATE = 'UPDATE';
export const ADDTOSCHEDULE = 'ADDTOSCHEDULE';
export const COMPLETE = 'COMPLETE';
export const BOOKAPPOINTMENT = 'BOOKAPPOINTMENT';
export const DELETEAPPOINTMENT = 'DELETEAPPOINTMENT';
